var MOCK_DATA = {
  textbooks: [
    { id: 1, name: "高等数学（第七版）上册", subject: "数学" },
    { id: 2, name: "线性代数（第六版）", subject: "数学" },
    { id: 3, name: "概率论与数理统计", subject: "数学" },
  ],

  chapters: {
    1: [
      {
        id: 101,
        textbook_id: 1,
        parent_id: null,
        name: "第一章 函数与极限",
        sort_order: 1,
        children: [
          {
            id: 1011,
            textbook_id: 1,
            parent_id: 101,
            name: "§1.1 映射与函数",
            sort_order: 1,
            children: [],
          },
          {
            id: 1012,
            textbook_id: 1,
            parent_id: 101,
            name: "§1.2 数列的极限",
            sort_order: 2,
            children: [],
          },
          {
            id: 1013,
            textbook_id: 1,
            parent_id: 101,
            name: "§1.3 函数的极限",
            sort_order: 3,
            children: [],
          },
          {
            id: 1014,
            textbook_id: 1,
            parent_id: 101,
            name: "§1.4 无穷小与无穷大",
            sort_order: 4,
            children: [],
          },
          {
            id: 1015,
            textbook_id: 1,
            parent_id: 101,
            name: "§1.5 极限运算法则",
            sort_order: 5,
            children: [],
          },
          {
            id: 1016,
            textbook_id: 1,
            parent_id: 101,
            name: "§1.6 极限存在准则 两个重要极限",
            sort_order: 6,
            children: [],
          },
          {
            id: 1017,
            textbook_id: 1,
            parent_id: 101,
            name: "§1.7 无穷小的比较",
            sort_order: 7,
            children: [],
          },
          {
            id: 1018,
            textbook_id: 1,
            parent_id: 101,
            name: "§1.8 函数的连续性与间断点",
            sort_order: 8,
            children: [],
          },
        ],
      },
      {
        id: 102,
        textbook_id: 1,
        parent_id: null,
        name: "第二章 导数与微分",
        sort_order: 2,
        children: [
          {
            id: 1021,
            textbook_id: 1,
            parent_id: 102,
            name: "§2.1 导数概念",
            sort_order: 1,
            children: [],
          },
          {
            id: 1022,
            textbook_id: 1,
            parent_id: 102,
            name: "§2.2 函数的求导法则",
            sort_order: 2,
            children: [],
          },
          {
            id: 1023,
            textbook_id: 1,
            parent_id: 102,
            name: "§2.3 高阶导数",
            sort_order: 3,
            children: [],
          },
          {
            id: 1024,
            textbook_id: 1,
            parent_id: 102,
            name: "§2.4 隐函数及参数方程求导",
            sort_order: 4,
            children: [],
          },
        ],
      },
      {
        id: 103,
        textbook_id: 1,
        parent_id: null,
        name: "第三章 微分中值定理与导数的应用",
        sort_order: 3,
        children: [
          {
            id: 1031,
            textbook_id: 1,
            parent_id: 103,
            name: "§3.1 微分中值定理",
            sort_order: 1,
            children: [],
          },
          {
            id: 1032,
            textbook_id: 1,
            parent_id: 103,
            name: "§3.2 洛必达法则",
            sort_order: 2,
            children: [],
          },
          {
            id: 1033,
            textbook_id: 1,
            parent_id: 103,
            name: "§3.3 泰勒公式",
            sort_order: 3,
            children: [],
          },
        ],
      },
      {
        id: 104,
        textbook_id: 1,
        parent_id: null,
        name: "第四章 不定积分",
        sort_order: 4,
        children: [
          {
            id: 1041,
            textbook_id: 1,
            parent_id: 104,
            name: "§4.1 不定积分的概念与性质",
            sort_order: 1,
            children: [],
          },
          {
            id: 1042,
            textbook_id: 1,
            parent_id: 104,
            name: "§4.2 换元积分法",
            sort_order: 2,
            children: [],
          },
          {
            id: 1043,
            textbook_id: 1,
            parent_id: 104,
            name: "§4.3 分部积分法",
            sort_order: 3,
            children: [],
          },
        ],
      },
    ],
    2: [
      {
        id: 201,
        textbook_id: 2,
        parent_id: null,
        name: "第一章 行列式",
        sort_order: 1,
        children: [
          {
            id: 2011,
            textbook_id: 2,
            parent_id: 201,
            name: "§1.1 二阶与三阶行列式",
            sort_order: 1,
            children: [],
          },
          {
            id: 2012,
            textbook_id: 2,
            parent_id: 201,
            name: "§1.2 全排列与逆序数",
            sort_order: 2,
            children: [],
          },
          {
            id: 2013,
            textbook_id: 2,
            parent_id: 201,
            name: "§1.3 n阶行列式的定义",
            sort_order: 3,
            children: [],
          },
          {
            id: 2014,
            textbook_id: 2,
            parent_id: 201,
            name: "§1.4 行列式的性质",
            sort_order: 4,
            children: [],
          },
        ],
      },
      {
        id: 202,
        textbook_id: 2,
        parent_id: null,
        name: "第二章 矩阵及其运算",
        sort_order: 2,
        children: [
          {
            id: 2021,
            textbook_id: 2,
            parent_id: 202,
            name: "§2.1 矩阵的定义",
            sort_order: 1,
            children: [],
          },
          {
            id: 2022,
            textbook_id: 2,
            parent_id: 202,
            name: "§2.2 矩阵的运算",
            sort_order: 2,
            children: [],
          },
          {
            id: 2023,
            textbook_id: 2,
            parent_id: 202,
            name: "§2.3 逆矩阵",
            sort_order: 3,
            children: [],
          },
        ],
      },
      {
        id: 203,
        textbook_id: 2,
        parent_id: null,
        name: "第三章 向量组的线性相关性",
        sort_order: 3,
        children: [
          {
            id: 2031,
            textbook_id: 2,
            parent_id: 203,
            name: "§3.1 向量组及其线性组合",
            sort_order: 1,
            children: [],
          },
          {
            id: 2032,
            textbook_id: 2,
            parent_id: 203,
            name: "§3.2 向量组的线性相关性",
            sort_order: 2,
            children: [],
          },
        ],
      },
    ],
    3: [
      {
        id: 301,
        textbook_id: 3,
        parent_id: null,
        name: "第一章 随机事件与概率",
        sort_order: 1,
        children: [
          {
            id: 3011,
            textbook_id: 3,
            parent_id: 301,
            name: "§1.1 随机事件",
            sort_order: 1,
            children: [],
          },
          {
            id: 3012,
            textbook_id: 3,
            parent_id: 301,
            name: "§1.2 古典概型",
            sort_order: 2,
            children: [],
          },
          {
            id: 3013,
            textbook_id: 3,
            parent_id: 301,
            name: "§1.3 条件概率与独立性",
            sort_order: 3,
            children: [],
          },
        ],
      },
      {
        id: 302,
        textbook_id: 3,
        parent_id: null,
        name: "第二章 随机变量及其分布",
        sort_order: 2,
        children: [
          {
            id: 3021,
            textbook_id: 3,
            parent_id: 302,
            name: "§2.1 随机变量",
            sort_order: 1,
            children: [],
          },
          {
            id: 3022,
            textbook_id: 3,
            parent_id: 302,
            name: "§2.2 离散型随机变量",
            sort_order: 2,
            children: [],
          },
          {
            id: 3023,
            textbook_id: 3,
            parent_id: 302,
            name: "§2.3 连续型随机变量",
            sort_order: 3,
            children: [],
          },
        ],
      },
    ],
  },

  problems: {
    1011: [
      { id: 1, chapter_id: 1011, content: "设 $f(x) = \\frac{1}{1+x}$，求 $f[f(x)]$ 的表达式。", answer: "$f[f(x)] = \\frac{1+x}{2+x}$", source: "2024年高等数学期中考试 第1题" },
      { id: 2, chapter_id: 1011, content: "判断函数 $f(x) = \\ln(x + \\sqrt{1+x^2})$ 的奇偶性。", answer: "$f(-x) = \\ln(-x + \\sqrt{1+x^2}) = \\ln\\frac{1}{x+\\sqrt{1+x^2}} = -f(x)$，故为奇函数。", source: "2023年高等数学月考（一） 第3题" },
      { id: 3, chapter_id: 1011, content: "求函数 $y = \\arcsin\\frac{x-1}{2}$ 的定义域。", answer: "由 $\\left|\\frac{x-1}{2}\\right| \\leq 1$ 得 $-2 \\leq x-1 \\leq 2$，即定义域为 $[-1, 3]$。", source: "教材习题 1.1 第2题" },
    ],
    1012: [
      { id: 4, chapter_id: 1012, content: "用极限定义证明：$\\lim\\limits_{n\\to\\infty}\\frac{1}{n^2}=0$。", answer: "$\\forall\\varepsilon>0$，取 $N=\\left\\lceil\\frac{1}{\\sqrt{\\varepsilon}}\\right\\rceil$，当 $n>N$ 时有 $\\left|\\frac{1}{n^2}-0\\right|<\\varepsilon$。", source: "2022年高等数学期末考试 第2题" },
      { id: 5, chapter_id: 1012, content: "求极限 $\\lim\\limits_{n\\to\\infty}\\frac{2n^2+3n-1}{5n^2+2n+3}$。", answer: "分子分母同除以 $n^2$，得 $\\lim\\limits_{n\\to\\infty}\\frac{2+\\frac{3}{n}-\\frac{1}{n^2}}{5+\\frac{2}{n}+\\frac{3}{n^2}} = \\frac{2}{5}$。", source: "教材习题 1.2 第5题" },
    ],
    1013: [
      { id: 6, chapter_id: 1013, content: "求极限 $\\lim\\limits_{x\\to 0}\\frac{\\sin 3x}{x}$。", answer: "$\\lim\\limits_{x\\to 0}\\frac{\\sin 3x}{x} = \\lim\\limits_{x\\to 0}\\frac{3\\sin 3x}{3x} = 3$。", source: "2023年高等数学期中考试 第1题" },
      { id: 7, chapter_id: 1013, content: "求极限 $\\lim\\limits_{x\\to 0}\\frac{\\sqrt{1+x}-1}{x}$。", answer: "分子有理化：$\\lim\\limits_{x\\to 0}\\frac{(\\sqrt{1+x}-1)(\\sqrt{1+x}+1)}{x(\\sqrt{1+x}+1)} = \\lim\\limits_{x\\to 0}\\frac{1}{\\sqrt{1+x}+1} = \\frac{1}{2}$。", source: "2024年高等数学月考（二） 第4题" },
      { id: 8, chapter_id: 1013, content: "讨论函数 $f(x) = \\begin{cases} x\\sin\\frac{1}{x}, & x \\neq 0 \\\\ 0, & x = 0 \\end{cases}$ 在 $x=0$ 处的连续性。", answer: "$\\lim\\limits_{x\\to 0}x\\sin\\frac{1}{x}=0=f(0)$，故在 $x=0$ 处连续。", source: "2023年高等数学期末考试 第3题" },
    ],
    1014: [
      { id: 9, chapter_id: 1014, content: "当 $x\\to 0$ 时，比较 $\\tan x$ 与 $x$ 的阶数。", answer: "$\\lim\\limits_{x\\to 0}\\frac{\\tan x}{x}=1$，故 $\\tan x$ 与 $x$ 是同阶无穷小，且等价。", source: "教材习题 1.4 第1题" },
      { id: 10, chapter_id: 1014, content: "证明：当 $x\\to 0$ 时，$\\arcsin x \\sim x$。", answer: "$\\lim\\limits_{x\\to 0}\\frac{\\arcsin x}{x} \\xlongequal{t=\\arcsin x} \\lim\\limits_{t\\to 0}\\frac{t}{\\sin t} = 1$。", source: "2024年高等数学期中考试 第4题" },
    ],
    1015: [
      { id: 11, chapter_id: 1015, content: "求极限 $\\lim\\limits_{x\\to 1}\\frac{x^2-1}{x-1}$。", answer: "$\\lim\\limits_{x\\to 1}\\frac{(x-1)(x+1)}{x-1} = \\lim\\limits_{x\\to 1}(x+1) = 2$。", source: "教材习题 1.5 第3题" },
    ],
    1016: [
      { id: 12, chapter_id: 1016, content: "求极限 $\\lim\\limits_{x\\to 0}\\frac{1-\\cos x}{x^2}$。", answer: "$\\lim\\limits_{x\\to 0}\\frac{1-\\cos x}{x^2} = \\lim\\limits_{x\\to 0}\\frac{2\\sin^2\\frac{x}{2}}{x^2} = \\frac{1}{2}\\lim\\limits_{x\\to 0}\\frac{\\sin^2\\frac{x}{2}}{(\\frac{x}{2})^2} = \\frac{1}{2}$。", source: "2022年高等数学期中考试 第2题" },
      { id: 13, chapter_id: 1016, content: "求极限 $\\lim\\limits_{x\\to 0}\\frac{\\sin 2x}{\\sin 3x}$。", answer: "$\\lim\\limits_{x\\to 0}\\frac{\\sin 2x}{\\sin 3x} = \\lim\\limits_{x\\to 0}\\frac{2x\\cdot\\frac{\\sin 2x}{2x}}{3x\\cdot\\frac{\\sin 3x}{3x}} = \\frac{2}{3}$。", source: "教材习题 1.6 第4题" },
      { id: 14, chapter_id: 1016, content: "求极限 $\\lim\\limits_{x\\to \\infty}\\left(1+\\frac{1}{x}\\right)^{2x}$。", answer: "$\\lim\\limits_{x\\to \\infty}\\left(1+\\frac{1}{x}\\right)^{2x} = \\left[\\lim\\limits_{x\\to \\infty}\\left(1+\\frac{1}{x}\\right)^x\\right]^2 = e^2$。", source: "2024年高等数学期末考试 第1题" },
    ],
    1017: [
      { id: 15, chapter_id: 1017, content: "当 $x\\to 0$ 时，求 $\\sin x - x$ 的主部及阶数。", answer: "$\\sin x = x - \\frac{x^3}{6} + o(x^3)$，故 $\\sin x - x \\sim -\\frac{x^3}{6}$，为 3 阶无穷小。", source: "2023年高等数学期中考试 第5题" },
    ],
    1018: [
      { id: 16, chapter_id: 1018, content: "求函数 $f(x)=\\frac{x^2-1}{x^2-3x+2}$ 的间断点并判断类型。", answer: "分母零点 $x=1,2$。$x=1$ 处：$\\lim\\limits_{x\\to 1}f(x)=-2$，为可去间断点；$x=2$ 处：$\\lim\\limits_{x\\to 2}f(x)=\\infty$，为无穷间断点。", source: "2024年高等数学月考（三） 第2题" },
    ],
    1021: [
      { id: 17, chapter_id: 1021, content: "用导数定义求 $f(x)=x^2$ 在 $x=1$ 处的导数。", answer: "$f'(1)=\\lim\\limits_{\\Delta x\\to 0}\\frac{(1+\\Delta x)^2-1}{\\Delta x}=\\lim\\limits_{\\Delta x\\to 0}(2+\\Delta x)=2$。", source: "教材习题 2.1 第1题" },
      { id: 18, chapter_id: 1021, content: "求曲线 $y=x^3$ 在点 $(1,1)$ 处的切线方程。", answer: "$y'=3x^2$，$y'(1)=3$，切线方程为 $y-1=3(x-1)$，即 $y=3x-2$。", source: "2023年高等数学期中考试 第6题" },
    ],
    1022: [
      { id: 19, chapter_id: 1022, content: "求导数：$y = e^{2x}\\sin 3x$。", answer: "$y' = 2e^{2x}\\sin 3x + e^{2x}\\cdot 3\\cos 3x = e^{2x}(2\\sin 3x + 3\\cos 3x)$。", source: "2024年高等数学期末考试 第3题" },
      { id: 20, chapter_id: 1022, content: "求导数：$y = \\ln(1+x^2)$。", answer: "$y' = \\frac{2x}{1+x^2}$。", source: "教材习题 2.2 第5题" },
    ],
    1023: [
      { id: 21, chapter_id: 1023, content: "求 $y=x^2\\sin x$ 的 $y^{(10)}(0)$。", answer: "利用莱布尼茨公式，$y^{(10)}(0)=C_{10}^2\\cdot 2!\\cdot (\\sin x)^{(8)}|_{x=0}=90\\cdot\\sin 0=0$。", source: "2022年高等数学期中考试 第7题" },
    ],
    1024: [
      { id: 22, chapter_id: 1024, content: "设 $y=y(x)$ 由方程 $x^2+y^2=1$ 确定，求 $\\frac{dy}{dx}$。", answer: "两边对 $x$ 求导：$2x+2yy'=0$，得 $y'=-\\frac{x}{y}$。", source: "教材习题 2.4 第2题" },
    ],
    1031: [
      { id: 23, chapter_id: 1031, content: "验证函数 $f(x)=\\sin x$ 在 $[0,\\pi]$ 上满足罗尔定理条件，并求 $\\xi$。", answer: "$f(0)=0$，$f(\\pi)=0$，$f'(x)=\\cos x$，令 $\\cos\\xi=0$ 得 $\\xi=\\frac{\\pi}{2}\\in(0,\\pi)$。", source: "教材习题 3.1 第1题" },
      { id: 24, chapter_id: 1031, content: "用拉格朗日中值定理证明：$|\\sin a - \\sin b| \\leq |a-b|$。", answer: "$\\sin a - \\sin b = \\cos\\xi\\cdot(a-b)$，$|\\cos\\xi|\\leq 1$，故 $|\\sin a - \\sin b| \\leq |a-b|$。", source: "2023年高等数学期末考试 第4题" },
    ],
    1032: [
      { id: 25, chapter_id: 1032, content: "求极限 $\\lim\\limits_{x\\to 0}\\frac{e^x-1-x}{x^2}$。", answer: "用洛必达法则：$\\lim\\limits_{x\\to 0}\\frac{e^x-1}{2x} = \\lim\\limits_{x\\to 0}\\frac{e^x}{2} = \\frac{1}{2}$。", source: "2024年高等数学期中考试 第3题" },
      { id: 26, chapter_id: 1032, content: "求极限 $\\lim\\limits_{x\\to 0^+}x\\ln x$。", answer: "$\\lim\\limits_{x\\to 0^+}x\\ln x = \\lim\\limits_{x\\to 0^+}\\frac{\\ln x}{1/x} \\xlongequal{\\text{L'H}} \\lim\\limits_{x\\to 0^+}\\frac{1/x}{-1/x^2} = \\lim\\limits_{x\\to 0^+}(-x)=0$。", source: "教材习题 3.2 第4题" },
    ],
    1033: [
      { id: 27, chapter_id: 1033, content: "求 $f(x)=e^x$ 的 $n$ 阶麦克劳林公式。", answer: "$e^x = 1+x+\\frac{x^2}{2!}+\\cdots+\\frac{x^n}{n!}+\\frac{e^{\\theta x}}{(n+1)!}x^{n+1}$，$0<\\theta<1$。", source: "2023年高等数学期中考试 第8题" },
    ],
    1041: [
      { id: 28, chapter_id: 1041, content: "求不定积分 $\\int (3x^2+2x+1)dx$。", answer: "$\\int (3x^2+2x+1)dx = x^3+x^2+x+C$。", source: "教材习题 4.1 第1题" },
    ],
    1042: [
      { id: 29, chapter_id: 1042, content: "求不定积分 $\\int x\\sin(x^2)dx$。", answer: "令 $u=x^2$，$du=2xdx$，原式 $=\\frac{1}{2}\\int\\sin u du = -\\frac{1}{2}\\cos(x^2)+C$。", source: "2024年高等数学期末考试 第5题" },
      { id: 30, chapter_id: 1042, content: "求不定积分 $\\int \\frac{1}{\\sqrt{1-x^2}}dx$。", answer: "$\\int \\frac{1}{\\sqrt{1-x^2}}dx = \\arcsin x + C$。", source: "教材习题 4.2 第3题" },
    ],
    1043: [
      { id: 31, chapter_id: 1043, content: "求不定积分 $\\int x e^x dx$。", answer: "分部积分：$\\int x e^x dx = x e^x - \\int e^x dx = (x-1)e^x + C$。", source: "2023年高等数学期末考试 第6题" },
      { id: 32, chapter_id: 1043, content: "求不定积分 $\\int \\ln x dx$。", answer: "分部积分：$\\int \\ln x dx = x\\ln x - \\int x\\cdot\\frac{1}{x}dx = x\\ln x - x + C$。", source: "教材习题 4.3 第2题" },
    ],
    2011: [
      { id: 33, chapter_id: 2011, content: "计算行列式 $\\begin{vmatrix} 1 & 2 \\\\ 3 & 4 \\end{vmatrix}$。", answer: "$1\\times4 - 2\\times3 = 4 - 6 = -2$。", source: "教材习题 1.1 第1题" },
      { id: 34, chapter_id: 2011, content: "解方程 $\\begin{vmatrix} x & 1 \\\\ 2 & x \\end{vmatrix} = 0$。", answer: "$x^2-2=0$，$x=\\pm\\sqrt{2}$。", source: "2024年线性代数期中考试 第1题" },
    ],
    2012: [
      { id: 35, chapter_id: 2012, content: "求排列 3 1 4 2 的逆序数。", answer: "逆序：$(3,1),(3,2),(4,2)$，共 3 个。", source: "教材习题 1.2 第1题" },
    ],
    2013: [
      { id: 36, chapter_id: 2013, content: "用行列式定义计算 $\\begin{vmatrix} 0 & 0 & 1 \\\\ 0 & 2 & 0 \\\\ 3 & 0 & 0 \\end{vmatrix}$。", answer: "$1\\times2\\times3\\times(-1)^{\\tau(3,2,1)} = 6\\times(-1)^{3} = -6$。", source: "2023年线性代数期末考试 第2题" },
    ],
    2014: [
      { id: 37, chapter_id: 2014, content: "利用行列式性质计算 $\\begin{vmatrix} a & b & c \\\\ a^2 & b^2 & c^2 \\\\ a^3 & b^3 & c^3 \\end{vmatrix}$。", answer: "提公因式得 $abc\\begin{vmatrix} 1 & 1 & 1 \\\\ a & b & c \\\\ a^2 & b^2 & c^2 \\end{vmatrix} = abc(b-a)(c-a)(c-b)$。", source: "2024年线性代数期中考试 第3题" },
    ],
    2021: [
      { id: 38, chapter_id: 2021, content: "已知 $A=\\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \\end{pmatrix}$，$B=\\begin{pmatrix} 2 & 0 \\\\ 1 & 3 \\end{pmatrix}$，求 $A+B$。", answer: "$A+B = \\begin{pmatrix} 3 & 2 \\\\ 4 & 7 \\end{pmatrix}$。", source: "教材习题 2.1 第1题" },
    ],
    2022: [
      { id: 39, chapter_id: 2022, content: "设 $A=\\begin{pmatrix} 1 & 1 \\\\ 0 & 1 \\end{pmatrix}$，求 $A^n$。", answer: "$A^n = \\begin{pmatrix} 1 & n \\\\ 0 & 1 \\end{pmatrix}$。", source: "2023年线性代数期中考试 第4题" },
    ],
    2023: [
      { id: 40, chapter_id: 2023, content: "求矩阵 $A=\\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \\end{pmatrix}$ 的逆矩阵。", answer: "$A^{-1} = \\frac{1}{-2}\\begin{pmatrix} 4 & -2 \\\\ -3 & 1 \\end{pmatrix} = \\begin{pmatrix} -2 & 1 \\\\ \\frac{3}{2} & -\\frac{1}{2} \\end{pmatrix}$。", source: "2024年线性代数期末考试 第2题" },
    ],
    2031: [
      { id: 41, chapter_id: 2031, content: "判断向量组 $\\alpha_1=(1,0), \\alpha_2=(0,1), \\alpha_3=(1,1)$ 的线性相关性。", answer: "3 个二维向量必线性相关。事实上 $\\alpha_1+\\alpha_2-\\alpha_3=0$。", source: "教材习题 3.1 第2题" },
    ],
    2032: [
      { id: 42, chapter_id: 2032, content: "判断向量组 $\\alpha_1=(1,1,0), \\alpha_2=(1,0,1), \\alpha_3=(0,1,1)$ 的线性相关性。", answer: "设 $k_1\\alpha_1+k_2\\alpha_2+k_3\\alpha_3=0$，解得 $k_1=k_2=k_3=0$，故线性无关。", source: "2023年线性代数期末考试 第3题" },
    ],
    3011: [
      { id: 43, chapter_id: 3011, content: '写出掷一颗骰子的样本空间，并写出事件"出现奇数点"。', answer: "样本空间 $\\Omega=\\{1,2,3,4,5,6\\}$，事件 $A=\\{1,3,5\\}$。", source: "教材习题 1.1 第1题" },
    ],
    3012: [
      { id: 44, chapter_id: 3012, content: "袋中有 3 个白球 2 个黑球，任取 2 个，求 2 个都是白球的概率。", answer: "$P = \\frac{C_3^2}{C_5^2} = \\frac{3}{10}$。", source: "2024年概率论期中考试 第2题" },
    ],
    3013: [
      { id: 45, chapter_id: 3013, content: "已知 $P(A)=0.5$，$P(B)=0.4$，$P(A\\cap B)=0.2$，求 $P(A|B)$。", answer: "$P(A|B) = \\frac{P(A\\cap B)}{P(B)} = \\frac{0.2}{0.4} = 0.5$。", source: "教材习题 1.3 第3题" },
      { id: 46, chapter_id: 3013, content: "甲乙独立射击，命中率分别为 0.8 和 0.7，求目标被击中的概率。", answer: "$P = 1 - (1-0.8)(1-0.7) = 1 - 0.06 = 0.94$。", source: "2023年概率论期末考试 第1题" },
    ],
    3021: [
      { id: 47, chapter_id: 3021, content: "设随机变量 $X$ 的分布律为 $P(X=k)=\\frac{c}{k!}, k=0,1,2,\\cdots$，求常数 $c$。", answer: "$\\sum\\limits_{k=0}^{\\infty}\\frac{c}{k!}=c\\cdot e=1$，得 $c=e^{-1}$。", source: "2024年概率论期中考试 第4题" },
    ],
    3022: [
      { id: 48, chapter_id: 3022, content: "设 $X\\sim B(3,0.4)$，求 $P(X=2)$。", answer: "$P(X=2) = C_3^2(0.4)^2(0.6)^1 = 3\\times0.16\\times0.6 = 0.288$。", source: "教材习题 2.2 第2题" },
    ],
    3023: [
      { id: 49, chapter_id: 3023, content: "设 $X\\sim N(0,1)$，求 $P(-1 \\lt X \\lt 2)$。（已知 $\\Phi(1)=0.8413$，$\\Phi(2)=0.9772$）", answer: "$P(-1 \\lt X \\lt 2) = \\Phi(2)-\\Phi(-1) = \\Phi(2)-(1-\\Phi(1)) = 0.9772 - (1-0.8413) = 0.8185$。", source: "2023年概率论期末考试 第4题" },
    ],
  },
};
